sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - rpm
script:
  - mvn test verify -Dmaven.javadoc.skip=true -B -V
before_deploy:
  - find . -type f -name 'original-*.jar' -delete
  - mvn jdeb:jdeb
  - mvn rpm:rpm
deploy:
  provider: releases
  api_key:
    secure: E0ih9UbnXzBWpjk5/+6Qp+79Szwhaklq7ytKILjTwviItWEEkKTbMCaB5QdfG4bd2sJs18sxuDwHoMT+21oX2+P9vBE4dWiYhFgpqFlOEz3CKRq2hS7v84Gf2NVMLxfUVzn1TXOYq1fDbmnRCmy8kk7PWwQRTQgSLbaZ708Gx6R9XyD2y0FXhWO9NwCrrJ/RO+aDQ/g9tTSXNQ7ncwVHess/OgtOJiCEJ2LXYzYUGJSUHlMVVVER4tX/apz4DK57SLtvz+3OvtuxsMG/xSjKkOYG6GHbzBGGellPqxhv9OWYw5vpSTPl9jpm/CAB5dUqgKFFeykh2Z40bB7sTl+zlf4Jpg6zrmEINXZPT9cc5HclPeTc6QeUyjnYLJUHO7VKUDeyv1rZ/cm1bdG9s4judHHaQk0AoyjWGwADVT/ip4JRLnJznNN7z0HT+i6zCeZ2scEY+tXVzcLXuNt1ZuqQkD2TnFv1mBTRJE76eSGYJY9WKs8aaiSZHUcOAFAdBdGOgpH5W0YN0gTeFBwD2NnlpH/pebxrQby5vyUEd8f4r43RR84Cu3iUEIPF6+HSIfuyEcjgISLk8aABZ6rMWE/n0hVoLAK4mu8CkL2WaDz+GM3byKOjLeztX4g+5wkOCPVZb7WT+/Ur09uY7nlYnthDlwZJY2je5CGaI0oOMAcxRYw=
  file_glob: true
  file:
    - "**/target/*.jar"
    - "**/target/*.deb"
    - "**/target/**/*.rpm"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
    repo: Graylog2/graylog-plugin-internal-logs
